site: cmac4603
title: cmac4603
greetings: Hi 👋
description: >-
  Developer diary & blog
lang: en-US
timezone:  Europe/London
repo: https://github.com/cmac4603.github.io]
data-theme: dark

author:
  name: cmac4603
  bio: Software developer // devops engineer
  userpicture:
  username: cmac4603
  github: cmac4603
  twitter: cmac4603
  email: me@cmac4603.dev

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://cmac4603.github.io"
baseurl: ""
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
